version: '3'
services:
  mailhog:
    image: mailhog/mailhog:v1.0.0
    ports:
      - '8025:8025'
  db:
    image: postgres
    environment: 
      - POSTGRES_PASSWORD=password
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  web:
    tty: true
    stdin_open: true
    build: .
    env_file: my_env_file.env
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      SMTP_HOST: mailhog
      SMTP_PORT: 1025
    volumes:
      - .:/myapp
      - /myapp/vendor
      - /myapp/tmp
      - /myapp/log
      - /myapp/.git
    ports:
      - "3000:3000"
    depends_on:
      - db
      - chrome
      - mailhog
  chrome:
    image: selenium/standalone-chrome-debug:latest
    ports:
      - 5900:5900
