version: '3'
services:
  db:
    image: postgres
    environment: 
      POSTGRES_HOST_AUTH_METHOD: 'trust'
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    tty: true
    stdin_open: true
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
      - /myapp/vendor
      - /myapp/tmp
      - /myapp/log
      - /myapp/.git
    ports:
      - "3000:3000"
    depends_on:
      - db